version: "3.3"

services:
  php-fpm:
    restart: unless-stopped
    container_name: ayax_php
    build:
      context: ./php-fpm
      dockerfile: Dockerfile
    volumes:
      - ${PROJECTS_PATH}:/var/www
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "10"
      
  nginx:
    restart: unless-stopped
    container_name: ayax_nginx
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf.${CURRENT_ENV}:/etc/nginx/conf.d/
      - ${PROJECTS_PATH}:/var/www
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "10"

  mysql_db:
    restart: unless-stopped
    container_name: ayax_mysql_db
    build:
      context: ./mysql
      dockerfile: Dockerfile
    volumes:
      - ${DATA_PATH}/mysql:/var/lib/mysql
      - ${DUMPS_PATH}:/dumps
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    command: --character-set-server=utf8 --collation-server=utf8_general_ci
    ports:
      - "3306:3306"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "10"
    
  node: 
    restart: unless-stopped
    container_name: ayax_node
    build:
      context: ./node
      dockerfile: Dockerfile
    volumes:
      - ${PROJECTS_PATH}:/var/www
    command: sh -c "npm install && npm run watch-poll"